export enum ErrorCode {
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_IS_DUPLICATED = 'USER_EMAIL_IS_DUPLICATED',
  USER_EMAIL_DO_NOT_EXIST = 'USER_EMAIL_DO_NOT_EXIST',
  USER_PASSWORD_IS_WRONG = 'USER_PASSWORD_IS_WRONG',
  EXPENSE_INVALID_CATEGORY_ID = 'EXPENSE_INVALID_CATEGORY_ID',
  EXPENSE_NOT_FOUND = 'EXPENSE_NOT_FOUND',
  EXPENSE_MIN_MAX_AMOUNT_EXCLUSIVE = 'EXPENSE_MIN_MAX_AMOUNT_EXCLUSIVE',
  EXPENSE_MIN_AMOUNT_MORE_THAN_MAX = 'EXPENSE_MIN_AMOUNT_MORE_THAN_MAX',
}
