export enum ErrorCode {
  // 400
  MISSING_PARAMETER = 'MISSING_PARAMETER',
  OUT_OF_RANGE = 'OUT_OF_RANGE',

  // budget
  BUDGET_YEAR_OUT_OF_RANGE = 'BUDGET_YEAR_OUT_OF_RANGE',
  BUDGET_MONTH_OUT_OF_RANGE = 'BUDGET_MONTH_OUT_OF_RANGE',
  BUDGET_INVALID_BUDGETS = 'BUDGET_INVALID_BUDGETS',
  BUDGET_AMOUNT_OUT_OF_RANGE = 'BUDGET_AMOUNT_OUT_OF_RANGE',
  BUDGET_TOTAL_AMOUNT_OUT_OF_RANGE = 'BUDGET_TOTAL_AMOUNT_OUT_OF_RANGE',
  BUDGET_BUDGETS_OUT_OF_RANGE = 'BUDGET_BUDGETS_OUT_OF_RANGE',

  // category
  CATEGORY_INVALID_ID = 'CATEGORY_INVALID_ID',

  // stat
  STAT_INVALID_VIEW = 'STAT_INVALID_VIEW',

  // tx
  TX_INVALID_TX_TYPE = 'TX_INVALID_TX_TYPE',
  TX_INVALID_TX_METHOD = 'TX_INVALID_TX_METHOD',
  TX_INVALID_AMOUNT = 'TX_INVALID_AMOUNT',
  TX_INVALID_DATE = 'TX_INVALID_DATE',
  TX_INVALID_DESCRIPTION = 'TX_INVALID_DESCRIPTION',
  TX_INVALID_IS_EXCLUDED = 'TX_INVALID_IS_EXCLUDED',
  TX_AMOUNT_OUT_OF_RANGE = 'TX_AMOUNT_OUT_OF_RANGE',
  TX_DESCRIPTION_OUT_OF_LENGTH = 'TX_DESCRIPTION_OUT_OF_LENGTH',
  TX_INVALID_START_DATE = 'TX_INVALID_START_DATE',
  TX_INVALID_END_DATE = 'TX_INVALID_END_DATE',

  // user
  USER_INVALID_NICKNAME = 'USER_INVALID_NICKNAME',
  USER_NICKNAME_OUT_OF_RANGE = 'USER_NICKNAME_OUT_OF_RANGE',

  // FIXME: auth 변경
  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_NICKNAME_TYPE = 'INVALID_NICKNAME_TYPE',
  INVALID_NICKNAME_LENGTH = 'INVALID_NICKNAME_LENGTH',

  // 401
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  USER_EMAIL_DO_NOT_EXIST = 'USER_EMAIL_DO_NOT_EXIST',
  USER_PASSWORD_IS_WRONG = 'USER_PASSWORD_IS_WRONG',

  // 403
  TX_FORBIDDEN = 'TX_FORBIDDEN',
  BUDGET_FORBIDDEN = 'BUDGET_FORBIDDEN',

  // 404
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EXPENSE_NOT_FOUND = 'EXPENSE_NOT_FOUND',
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',

  // 409
  USER_EMAIL_IS_DUPLICATED = 'USER_EMAIL_IS_DUPLICATED',
  BUDGET_IS_DUPLICATED = 'BUDGET_IS_DUPLICATED',
}
